name: Quality

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.8
        with:
          cache: true
          locked: true

      - name: Run pre-commit
        run: pixi run precommit

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.8
        with:
          cache: true
          locked: true

      - name: Run ty
        run: pixi run typecheck
